eval_fp: /project/learningphysics/torch_dataset/20210905_4/atv_20210905_eval/
experiment_fp: /data/datasets/striest/experiments
latent_model:
  params:
    act_encoder_hidden_size:
    - 16
    - 16
    mlp_decoder_hidden_size:
    - 128
    mlp_encoder_hidden_size: []
    rnn_hidden_size: 128
    rnn_layers: 1
  type: ProbWorldModel
lr: 0.001
modalities:
  frontcam:
    decoder:
      params:
        channels:
        - 1
      type: CNNDecoder
    encoder:
      params:
        channels:
        - 4
        - 8
        - 16
        - 32
      type: CNNEncoder
    loss:
      params:
        scale: 100.0
      type: NoLoss
    topic: image_rgb
  heightmap:
    decoder:
      params:
        channels:
        - 1
      type: CNNDecoder
    encoder:
      params:
        channels:
        - 4
        - 8
        - 16
        - 32
      type: CNNEncoder
    loss:
      params:
        scale: 1.0
      type: NoLoss
    topic: heightmap
  imu:
    decoder:
      params:
        hidden_dims:
        - 1
        scales:
        - 2
      type: WaveNetDecoder
    encoder:
      params:
        dilations:
        - 2
        - 4
        - 8
        - 16
        hidden_dims:
        - 9
        - 9
        - 9
        - 9
        kernel_sizes:
        - 2
        - 2
        - 2
        - 2
      type: WaveNetEncoder
    loss:
      params:
        scale: 0.1
      type: NoLoss
    topic: imu
  rgbmap:
    decoder:
      params:
        channels:
        - 1
      type: CNNDecoder
    encoder:
      params:
        channels:
        - 4
        - 8
        - 16
        - 32
      type: CNNEncoder
    loss:
      params:
        scale: 100.0
      type: NoLoss
    topic: rgbmap
  wheel_rpm:
    decoder:
      params:
        hidden_dims:
        - 1
        scales:
        - 2
      type: WaveNetDecoder
    encoder:
      params:
        dilations:
        - 2
        - 4
        - 8
        - 16
        hidden_dims:
        - 9
        - 9
        - 9
        - 9
        kernel_sizes:
        - 2
        - 2
        - 2
        - 2
      type: WaveNetEncoder
    loss:
      params:
        scale: 0.1
      type: NoLoss
    topic: wheel_rpm
name: contrastive_atv_all_t20
save_every: 50
train_fp: /project/learningphysics/torch_dataset/20210905_4/atv_20210905_train/
trainer:
  params:
    batch_size: 64
    contrastive_scale: 10.0
    ema: 0.05
    epochs: 5000
    model_itrs: 10
    n_eval_steps: 20
    n_steps: 20
  type: LatentProbWorldModelsTrainer
